<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\..\..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	
	<!-- analyzers -->
	<ItemGroup>
	  <ProjectReference Include="..\SourceGeneration\SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Assets\Shaders\" />
	  <Folder Include="Assets\Textures\" />
	</ItemGroup>

</Project>