<Project Sdk="Tomat.Terraria.ModLoader.Sdk">

    <Import Project="../../build/Mod.Build.targets"/>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
        <TmlBuildUseDefaultModImpl>false</TmlBuildUseDefaultModImpl>
        <TargetFramework>net10.0</TargetFramework>
        <TmlVersion>dev</TmlVersion>
    </PropertyGroup>
    
</Project>