/* MIT License
 * 
 * Copyright (c) 2021 Steven Sell
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.*/

using Microsoft.Xna.Framework;
using System;
using System.Collections.Generic;
using Terraria.Utilities;

namespace WorldGenSandbox.Utilities;

/// <summary>
/// A poisson disk sampler (blue noise) where the sample radius (minimum distance between points) is variable.<para/>
/// If the radius is constant, then <see cref="UniformPoissonSampler2D"/> should be used instead for better performance.
/// </summary>
public sealed class VariablePoissonSampler2D
{
    // ---------------------------------------------------------------------------------
    // Properties
    // ---------------------------------------------------------------------------------

    /// <summary>
    /// Is the poisson sampler currently in progress? If so, any calls to <see cref="Generate"/> will fail.
    /// </summary>
    public bool IsGenerating { get; private set; }

    /// <summary>
    /// The sample point generated by the sampler.
    /// </summary>
    public List<Sample2D> Samples { get; private set; }

    /// <summary>
    /// The width of the domain of the sampler. This is the maximum <c>x</c> value in a generated point.
    /// </summary>
    public float Width { get { return MaxPoint.X; } }

    /// <summary>
    /// The height of the domain of the sampler. This is the maximum <c>y</c> value in a generated point.
    /// </summary>
    public float Height { get { return MaxPoint.Y; } }

    /// <summary>
    /// The maximum number of attempts to generate a valid new point.
    /// The higher this value, the higher the coverage of the sampler but an increased runtime cost.
    /// </summary>
    public int RejectionLimit { get; private set; }

    /// <summary>
    /// Represents the bounds of the sampler region, on the range <c>[(0, 0), (MaxPoint.x, MaxPoint.y)]</c>.
    /// </summary>
    private Vector2 MaxPoint;

    /// <summary>
    /// The RNG used to generate the points in the sampled annulus.
    /// </summary>
    private UnifiedRandom Rng;

    /// <summary>
    /// 
    /// </summary>
    private SpatialGrid2D<int> SpatialGrid;

    /// <summary>
    /// List of candidate points that we will try to generate new points around.
    /// </summary>
    private List<int> ActiveList;

    // ---------------------------------------------------------------------------------
    // Delegates
    // ---------------------------------------------------------------------------------

    public delegate float GetRadiusAt(float x, float y);

    public delegate bool IsInBounds(float x, float y);

    // ---------------------------------------------------------------------------------
    // Methods
    // ---------------------------------------------------------------------------------

    /// <param name="rng">The RNG used to generate the random points.</param>
    /// <param name="width">The width of the sampler domain. The maximum x value of a sampled position will be this.</param>
    /// <param name="height">The height of the sampler domain. The maximum y value of a sampled position will be this.</param>
    /// <param name="rejectionLimit">Number of generation attempts before a prospective point is rejected.</param>
    public VariablePoissonSampler2D(UnifiedRandom rng, float width, float height, int rejectionLimit = 30)
    {
        Rng = rng;
        RejectionLimit = rejectionLimit;
        MaxPoint = new Vector2(width, height);
    }

    /// <summary>
    /// Fills the sample domain with blue noise distributed points.
    /// Once generation is complete the results can be obtained from <see cref="SamplesList"/>.
    /// </summary>
    /// <param name="minRadius">The minimum minimum distance between points. This is not enforced but used for optimizations.</param>
    /// <param name="maxRadius">The maximum minimum distance between points. This is not enforced but used for optimizations.</param>
    /// <returns></returns>
    public bool Generate(GetRadiusAt radiusFunc, IsInBounds boundsFunc)
    {
        if (!IsGenerating)
            return false;

        if (ActiveList.Count == 0)
        {
            for (int i = 0; i < Samples.Count; i++)
                ActiveList.Add(i);
        }

        while (ActiveList.Count > 0)
        {
            bool sampleFound = false;
            int activeIndex = GetRandomActiveListIndex();

            Sample2D currentSample = Samples[ActiveList[activeIndex]];

            ref Vector2 samplePosition = ref currentSample.Position;
            ref float sampleRadius = ref currentSample.Radius;

            for (int i = 0; i < RejectionLimit; ++i)
            {
                float radius = radiusFunc(samplePosition.X, samplePosition.Y);
                Vector2 randomSample = GenerateRandomPointInAnnulus(ref samplePosition, radius);

                if (!boundsFunc(randomSample.X, randomSample.Y))
                    continue;

                if (SpatialGrid.AddIfOpen(Samples.Count, randomSample.X, randomSample.Y, radius))
                {
                    AddSample(randomSample, radius);
                    sampleFound = true;

                    break;
                }
            }

            if (!sampleFound)
                ActiveList.RemoveUnorderedAt(activeIndex);
        }

        return true;
    }

    /// <summary>
    /// Initializes the sampler for a new run.
    /// </summary>
    public void Initialize(float minRadius, float maxRadius)
    {
        IsGenerating = true;

        SpatialGrid = new SpatialGrid2D<int>(Width, Height, minRadius, maxRadius);
        ActiveList = new List<int>(SpatialGrid.CellsPerX * SpatialGrid.CellsPerY);
        Samples = new List<Sample2D>();
    }

    /// <summary>
    /// Generates the first random point in the sample domain and adds it to our collections.
    /// </summary>
    /*private void GenerateFirstPoint()
    {
        Vector2 sample = new Vector2(
            (float)Rng.NextDouble() * MaxPoint.X,
            (float)Rng.NextDouble() * MaxPoint.Y);

        AddSample(ref sample);
    }*/

    /// <summary>
    /// Adds the new sample to the samples list and active list.
    /// </summary>
    /// <param name="sample"></param>
    public bool AddSample(Vector2 sample, float radius)
    {
        if (!IsGenerating)
            return false;

        int sampleIndex = Samples.Count;

        Samples.Add(new Sample2D(sample, radius));
        ActiveList.Add(sampleIndex);

        return true;
    }

    /// <summary>
    /// Retrieves a random index from the active list.
    /// </summary>
    /// <returns></returns>
    private int GetRandomActiveListIndex()
    {
        return Rng.Next(ActiveList.Count);
    }

    /// <summary>
    /// Generate a new random point in the annulus around the provided point.
    /// </summary>
    /// <param name="point"></param>
    /// <returns></returns>
    private Vector2 GenerateRandomPointInAnnulus(ref Vector2 point, float radius)
    {
        float min = radius;
        float max = radius * 2.0f;

        float distance = ((float)Rng.NextDouble() * (max - min)) + min;
        float angle = (float)Rng.NextDouble() * MathHelper.TwoPi;

        return new Vector2(
            point.X + ((float)Math.Cos(angle) * distance),
            point.Y + ((float)Math.Sin(angle) * distance));
    }
}